# Generated by Django 4.2.26 on 2025-11-29 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Task title/description", max_length=255
                    ),
                ),
                ("due_date", models.DateField(help_text="Task deadline")),
                (
                    "estimated_hours",
                    models.FloatField(
                        help_text="Estimated effort in hours",
                        validators=[django.core.validators.MinValueValidator(0.1)],
                    ),
                ),
                (
                    "importance",
                    models.IntegerField(
                        help_text="User-defined importance rating (1-10)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "dependencies",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of task IDs that this task depends on",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
